[versions]
agp = "8.13.2"
colorpickerCompose = "1.1.3"
emoji2Emojipicker = "1.6.0"
glance = "1.1.1"
koinAndroid = "4.1.1"
koinAndroidxCompose = "4.1.1"
koinAndroidxStartup = "4.1.1"
kotlin = "2.3.0"
activityCompose = "1.12.2"
coilCompose = "3.3.0"
composeBom = "2025.12.01"
composeAnimation = "1.10.0"
coreKtx = "1.17.0"
coreSplashscreen = "1.2.0"
datastorePreferences = "1.2.0"
kotlinxSerializationJson = "1.9.0"
materialKolor = "5.0.0-alpha04"
media3Common = "1.9.0"
media3Exoplayer = "1.9.0"
media3Session = "1.9.0"
reorderable = "3.0.0" # https://github.com/Calvin-LL/Reorderable
squigglyslider = "1.0.0"
serialization = "2.3.0"
taglib = "1.0.5"
roomCompiler = "2.8.4"
roomKtx = "2.8.4"
ksp = "2.3.3"
kmpalette = "3.1.0"
material3 = "1.5.0-alpha11"
nav3Core = "1.0.0"
lifecycleViewmodelNav3 = "2.10.0"
foundation = "1.10.0"





[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "composeAnimation" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-emoji2-emojipicker = { module = "androidx.emoji2:emoji2-emojipicker", version.ref = "emoji2Emojipicker" }
androidx-glance = { module = "androidx.glance:glance", version.ref = "glance" }
androidx-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-media3-common = { module = "androidx.media3:media3-common", version.ref = "media3Common" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Exoplayer" }
androidx-media3-session = { module = "androidx.media3:media3-session", version.ref = "media3Session" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
colorpicker-compose = { module = "com.github.skydoves:colorpicker-compose", version.ref = "colorpickerCompose" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinAndroidxCompose" }
koin-androidx-startup = { module = "io.insert-koin:koin-androidx-startup", version.ref = "koinAndroidxStartup" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
material-kolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }
squigglyslider = { module = "me.saket.squigglyslider:squigglyslider", version.ref = "squigglyslider" }
taglib = { module = "io.github.kyant0:taglib", version.ref = "taglib" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
kmpalette-core = { module = "com.kmpalette:kmpalette-core", version.ref = "kmpalette" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNav3" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }





[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization"}
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }